version: "3"

services:
  tams:
    container_name: tams
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: /bin/sh -c "node server.js"
    volumes:
      - node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_HOST

volumes:
  node_modules:
