version: "3"

services:
  tams:
    container_name: tams
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: /bin/sh -c "node app/server.js"
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_HOST=http://localhost:8000/api/v1/accounts

volumes:
  node_modules:
